services:
  - type: web
    name: firemongo
    runtime: image
    plan: free
    region: singapore
    image:
      url: ghcr.io/kayvanshah1/firebase-realtime-db-emulator:latest
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "10000"
      - key: DATABASE_NAME
        value: firebase_db
      - key: PROJECT_NAME
        value: FireMongo
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
