on: [push]

name: Deploy to Okteto

jobs:
  deploy-okteto:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - uses: okteto/context@latest
      name: Get the secrets
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        
    - name: "Build"
      uses: okteto/build@latest
      with:
        tag: kayvan999/firebase-realtime-db-emulator:${{ github.sha }}