on: 
  push:
    branches: 
      - "main"

name: Deploy to Okteto

jobs:
  deploy-okteto:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - uses: okteto/context@latest
      name: Get the secrets
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        
    - name: "Build"
      uses: okteto/build@latest
      with:
        tag: ${{ secrets.DOCKER_HUB_USERNAME }}/firebase-realtime-db-emulator:${{ github.sha }}

  build-and-push-to-dockerhub:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          load: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/firebase-realtime-db-emulator:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}